name: Testing Workflow

on:
  push:
    branches: [ "dev" ]
  pull_request:
    branches: [ "dev" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Docker Login
        uses: docker/login-action@v3.1.0
        with:
          username: ${{secrets.DOCKERHUB_NAME}}
          password: ${{secrets.DOCKERHUB_PWD}}
          
      - name: Build the Docker image
        uses: docker/build-push-action@v5.3.0
        with:
          push: true
          tags: innaxn/foody-ingress:latest
  redeploy:
      runs-on: self-hosted
      needs: build
      steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Apply Deployment
        run: kubectl apply -f k8s_deployment.yaml
      - name: Wait 2min (to be replaced with health-check)
        uses: juliangruber/sleep-action@v2.0.3
        with:
          time: 2m
